version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-4.10"
  jobs:
    post_create_environment:
      - unidep install .
    pre_build:
      # Generate the Sphinx configuration for this Jupyter Book so it builds.
      - "jupyter-book config sphinx docs/"

conda:
  environment: .rtd-environment.yml

formats:
  - htmlzip
  - pdf

sphinx:
  builder: html
  fail_on_warning: true
